modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All rights reserved"

[[mods]]
modId="enhanced_monster" 
version="${mod_version}"
displayName="Enhanced Monster" 
authors="Momo_EMT"
description='''
给予敌对生物梯度加成的药水效果。
'''

[[dependencies.enhanced_monster]] 
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhanced_monster]] 
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
